version: '3.2'

services:

  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SUBSTRATE_RPC_URL=${SUBSTRATE_RPC_URL}
      - SUBSTRATE_ADDRESS_TYPE=42
      - TYPE_REGISTRY_FILE=app/type_registry/metablockchain_types.json
      - SUBSTRATE_METADATA_VERSION=12
      - VALIDATOR_KEY=${VALIDATOR_KEY}
      - VALIDATOR_ISSUER=${VALIDATOR_ISSUER}
    depends_on:
      - mysql

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
      - ENVIRONMENT=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SUBSTRATE_RPC_URL=${SUBSTRATE_RPC_URL}
      - TYPE_REGISTRY_FILE=app/type_registry/metablockchain_types.json
      - SUBSTRATE_ADDRESS_TYPE=42
      - SUBSTRATE_METADATA_VERSION=12
      - NEW_SESSION_EVENT_HANDLER=True
      - SUBSTRATE_STORAGE_BALANCE=Did.Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
      - FINALIZATION_ONLY=1
    depends_on:
      - redis
      - mysql

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis
      - mysql

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile=""
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    ports:
      - '5555:5555'
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - ${DOCKER_DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: Metablockchain
        NETWORK_ID: ${NETWORK_ID}
        NETWORK_TYPE: pre
        CHAIN_TYPE: relay
        NETWORK_TOKEN_SYMBOL: MetaMUI
        NETWORK_TOKEN_DECIMALS: 6
        NETWORK_COLOR_CODE: 777777
        API_URL: ${EXPLORER_API_URL}
        SDK_API_URL: ${SDK_API_URL}
    ports:
    # We will use nginx proxy to route API & explorer requests
      - '8080:80'
    depends_on:
      - harvester-api
      - explorer-api

volumes:
  db-data:
